#!/bin/bash
#
# Copyright 2015 gisphm <phmfk@hotmail.com>
# Author: gisphm <phmfk@hotmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################
# Rebuilding script for updating snippets from #
# https://github.com/github/gitignore          #
################################################

build_dir="build"
repo_dir_name="github-gitignore"
repo_dir="$build_dir/$repo_dir_name"
snippets_dir="snippets/gitignore"
list_file="List.md"

echo "*** Rebuilding started ***"

# Preparing {{{

mkdir $build_dir
echo "$build_dir directory created"

echo "cloning gitignore from github"
git clone --depth 1 https://github.com/github/gitignore.git $repo_dir

# }}}

# Building {{{

echo "removing old snippets directory if it exists"
[[ -d "$snippets_dir" ]] && rm -rf snippets
[[ -f "$list_file" ]] && rm $list_file

echo "creating new snippets from gitignore files"
mkdir -p $snippets_dir
echo -e "# Snippets List" > $list_file
echo -e "\`\`\`" >> $list_file

generate_snippets() {
    local source_dir=$1
    local snippets_dir=$2
    for file in $source_dir/*.gitignore ; do
        local new_snippets_name="`basename "$file" .gitignore`"
        echo -e "$new_snippets_name" >> $list_file

        local new_snippets_file=$snippets_dir/"`basename "$file" .gitignore`.snippets"

        echo "snippet $new_snippets_name Gitignore Template" > $new_snippets_file
        echo "        ### $new_snippets_name ###" >> $new_snippets_file
        while read -r line ; do
            echo -e "        $line" >> $new_snippets_file
        done < $file
        echo -e "        \${0}" >> $new_snippets_file
    done
}

generate_snippets $repo_dir $snippets_dir
generate_snippets $repo_dir/Global $snippets_dir
echo -e "\`\`\`" >> $list_file

# }}}

# Clearing {{{

rm -rf build
echo "$build_dir directory removed"

# }}}

echo "*** Rebuilding completed ***"
