#!/bin/bash

################################################
# Rebuilding script for updating snippets from #
# https://github.com/github/gitignore          #
################################################

build_dir="build"
repo_dir_name="github-gitignore"
repo_dir="$build_dir/$repo_dir_name"
result_dir="snippets/gitignore"

echo "*** Rebuilding started ***"

# Preparing {{{

mkdir $build_dir
echo "$build_dir directory created"

git clone --depth 1 https://github.com/github/gitignore.git $repo_dir

# }}}

# Building {{{

mkdir -p $result_dir

for file_path in $repo_dir/*.gitignore
do
    echo >> "$file_path"
    new_snippets_name="`basename "$file_path" .gitignore`"
    new_snippets_file="`basename "$file_path" .gitignore`.snippets"
    echo "snippet $new_snippets_name" > $result_dir/$new_snippets_file
    for line in $(cat $file_path)
    do
        echo "    $line" >> $result_dir/$new_snippets_file
    done
done

for file_path in $repo_dir/Global/*.gitignore
do
    echo >> "$file_path"
    new_snippets_name="`basename "$file_path" .gitignore`"
    new_snippets_file="`basename "$file_path" .gitignore`.snippets"
    echo "snippet $new_snippets_name" > $result_dir/$new_snippets_file
    for line in $(cat $file_path)
    do
        echo "    $line" >> $result_dir/$new_snippets_file
    done
done

# }}}

# Clearing {{{

rm -rf build
echo "$build_dir directory removed"

# }}}

echo "*** Rebuilding completed ***"
